site_name: TXRX Doc Hub
site_url: https://niell-ion.github.io/RAR_Marmon_TXRX/
theme:
  name: material
  palette: 
    primary: deep orange
    accent: blue
nav:
  - Home: index.md
  - About: about.md
  - Projects:
    - RAR:
      - Table of Contents: rar/rar_toc.md
      - Preface: rar/rar_preface.md
      - System Overview: rar/rar_overview.md
      - Operations: rar/rar_operation.md
      - Maintenance: rar/rar_maintenance.md
      - Troubleshooting: rar/rar_troubleshooting.md
    - Switch Gap Detector:
      - Table of Contents: switchgap/switchgap_toc.md
      - Preface: switchgap/switchgap_preface.md
      - System Overview: switchgap/switchgap_overview.md
      - Operations: switchgap/switchgap_operation.md
      - Maintenance: switchgap/switchgap_maintenance.md
      - Troubleshooting: switchgap/switchgap_troubleshooting.md
    - Portable Crossing Gate:
      - Table of Contents: crossing/crossing_toc.md
      - Preface: crossing/crossing_preface.md
      - System Overview: crossing/crossing_overview.md
      - Setup: crossing/crossing_setup.md
      - Remote: crossing/crossing_remote.md
      - Maintenance: crossing/crossing_maintenance.md
      - Troubleshooting: crossing/crossing_troubleshooting.md
    - Derail:
      - Table of Contents: derail/derail_toc.md
markdown_extensions:
  - attr_list:
  - toc:
      permalink: true
